"""Opt-in live capability probe for the isolated customer_ceshi runtime.

This utility never prints credentials, response text, reasoning content, or raw provider IDs.
Run it only against a non-production test session with explicitly configured credentials.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

from openai import OpenAI


_CAPABILITIES = (
    "responses_basic", "deep_thinking", "function_call", "function_call_output", "call_id",
    "previous_response_id", "two_round_tools", "structured_output", "image_url", "audio_url",
    "video_url", "streaming", "context_cache", "context_editing", "chat_function_calling_fallback",
)


def _existing_statuses() -> dict[str, str]:
    path = Path("artifacts/customer_ceshi_capabilities.json")
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        statuses = payload.get("statuses") if isinstance(payload, dict) else {}
        return {str(name): str(value) for name, value in dict(statuses or {}).items()}
    except (OSError, TypeError, ValueError, json.JSONDecodeError):
        return {}


def _persist_artifacts(statuses: dict[str, str], probe_summary: dict[str, Any]) -> None:
    payload = {"generated_at": "2026-07-17", "statuses": statuses, "probe_summary": probe_summary}
    artifacts = Path("artifacts")
    docs = Path("docs")
    artifacts.mkdir(exist_ok=True)
    docs.mkdir(exist_ok=True)
    (artifacts / "customer_ceshi_capabilities.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    rows = "\n".join(f"| `{name}` | `{value}` |" for name, value in statuses.items())
    (docs / "customer_ceshi_capability_matrix.md").write_text(
        "# customer_ceshi Capability Matrix\n\n"
        "Generated by live Responses probes and safe OSS media E2E. Statuses represent executed evidence only.\n\n"
        "| Capability | Status |\n| --- | --- |\n" + rows + "\n",
        encoding="utf-8",
    )


def record_capability(name: str, *, passed: bool, kind: str) -> None:
    statuses = {name: "NOT_IMPLEMENTED" for name in _CAPABILITIES}
    statuses.update({name: value for name, value in _existing_statuses().items() if name in statuses})
    if name in statuses:
        statuses[name] = "PASSED" if passed else "FAILED"
    _persist_artifacts(statuses, {"kind": kind, "capability": name, "passed": passed})


def record_media_capability(media_type: str, *, passed: bool) -> None:
    record_capability(media_type, passed=passed, kind="safe_oss_media_e2e")


def _write_artifacts(result: dict[str, Any]) -> None:
    statuses = {name: "NOT_IMPLEMENTED" for name in _CAPABILITIES}
    statuses.update({name: value for name, value in _existing_statuses().items() if name in statuses})
    status = str(result.get("status") or "FAILED")
    statuses.update({
        "responses_basic": status,
        "function_call": status if result.get("function_call") else ("FAILED" if status == "PASSED" else status),
        "function_call_output": status if result.get("previous_response_id") else ("FAILED" if status == "PASSED" else status),
        "call_id": status if result.get("function_call") else ("FAILED" if status == "PASSED" else status),
        "previous_response_id": status if result.get("previous_response_id") else ("FAILED" if status == "PASSED" else status),
        "two_round_tools": status if result.get("previous_response_id") else ("FAILED" if status == "PASSED" else status),
        "deep_thinking": "PASSED" if result.get("deep_thinking") else ("FAILED" if result.get("deep_thinking") is False else "NOT_IMPLEMENTED"),
        "structured_output": "PASSED" if result.get("structured_output") else ("FAILED" if result.get("structured_output") is False else "NOT_IMPLEMENTED"),
        "streaming": "PASSED" if result.get("streaming") else ("FAILED" if result.get("streaming") is False else "NOT_IMPLEMENTED"),
        "context_cache": "PASSED" if result.get("context_cache") else ("FAILED" if result.get("context_cache") is False else "NOT_IMPLEMENTED"),
        "context_editing": "PASSED" if result.get("context_editing") else ("FAILED" if result.get("context_editing") is False else "NOT_IMPLEMENTED"),
    })
    multimodal_status = str((result.get("multimodal") or {}).get("status") or "SKIPPED")
    if multimodal_status != "SKIPPED":
        statuses["image_url"] = multimodal_status
    _persist_artifacts(statuses, result)


def _response_id(response: Any) -> str:
    return str(getattr(response, "id", "") or (response.get("id", "") if isinstance(response, dict) else ""))


def _calls(response: Any) -> list[dict[str, Any]]:
    output = getattr(response, "output", None) or (response.get("output", []) if isinstance(response, dict) else [])
    calls: list[dict[str, Any]] = []
    for item in output or []:
        item_type = getattr(item, "type", "") or (item.get("type", "") if isinstance(item, dict) else "")
        if item_type != "function_call":
            continue
        get = item.get if isinstance(item, dict) else lambda key, default=None: getattr(item, key, default)
        calls.append({"name": str(get("name", "")), "call_id": str(get("call_id", "") or get("id", ""))})
    return calls


def _output_text(response: Any) -> str:
    return str(getattr(response, "output_text", "") or (response.get("output_text", "") if isinstance(response, dict) else ""))


def _probe_multimodal_tools(*, api_key: str, base_url: str, tool: dict[str, Any]) -> dict[str, Any]:
    media_url = os.getenv("CUSTOMER_CESHI_MULTIMODAL_PROBE_URL", "").strip()
    if not media_url:
        return {"status": "SKIPPED", "reason": "set CUSTOMER_CESHI_MULTIMODAL_PROBE_URL to enable a public-image Doubao probe"}
    model = os.getenv("CUSTOMER_CESHI_MULTIMODAL_MODEL", "doubao-seed-2-1-pro-260628").strip()
    result = {"status": "FAILED", "responses": False, "function_call": False, "previous_response_id": False, "deep_thinking": None, "streaming": None, "error": ""}
    try:
        client = OpenAI(api_key=api_key, base_url=os.getenv("COZE_INTEGRATION_MULTIMODAL_BASE_URL", base_url).strip() or base_url)
        first = client.responses.create(
            model=model,
            input=[{"role": "user", "content": [
                {"type": "input_image", "image_url": media_url, "detail": "low"},
                {"type": "input_text", "text": "Call capability_echo exactly once with step 1. Do not answer in prose."},
            ]}],
            tools=[tool],
        )
        result["responses"] = bool(_response_id(first))
        calls = _calls(first)
        result["function_call"] = len(calls) == 1 and calls[0]["name"] == "capability_echo"
        if calls:
            second = client.responses.create(
                model=model,
                previous_response_id=_response_id(first),
                input=[{"type": "function_call_output", "call_id": calls[0]["call_id"], "output": json.dumps({"step": 1})}],
                tools=[tool],
            )
            result["previous_response_id"] = bool(_response_id(second))
        try:
            thought = client.responses.create(model=model, input="只回复：已收到。", thinking={"type": "enabled"})
            result["deep_thinking"] = bool(_response_id(thought))
        except Exception:
            result["deep_thinking"] = False
        try:
            events = client.responses.create(model=model, input="只回复：流式探测。", stream=True)
            result["streaming"] = any(True for _ in events)
        except Exception:
            result["streaming"] = False
        result["status"] = "PASSED" if all(result[key] for key in ("responses", "function_call", "previous_response_id")) else "FAILED"
    except Exception as exc:
        body = getattr(exc, "body", {})
        body = body if isinstance(body, dict) else {}
        error = body.get("error") if isinstance(body.get("error"), dict) else body
        details = [type(exc).__name__]
        if getattr(exc, "status_code", None) is not None:
            details.append(f"status={exc.status_code}")
        if isinstance(error, dict) and error.get("code"):
            details.append(f"code={str(error['code'])[:80]}")
        if isinstance(error, dict) and error.get("param"):
            details.append(f"param={str(error['param'])[:80]}")
        result["error"] = ";".join(details)
    return result


def main() -> int:
    if os.getenv("CUSTOMER_CESHI_REAL_MODEL_TEST", "").lower() not in {"1", "true", "yes"}:
        result = {"status": "SKIPPED", "reason": "set CUSTOMER_CESHI_REAL_MODEL_TEST=1 to enable live requests"}
        _write_artifacts(result)
        print(json.dumps(result, ensure_ascii=False))
        return 0
    api_key = os.getenv("COZE_WORKLOAD_IDENTITY_API_KEY", "").strip()
    base_url = os.getenv("COZE_INTEGRATION_MODEL_BASE_URL", "").strip()
    model = os.getenv("CUSTOMER_CESHI_RESPONSES_MODEL", "deepseek-v4-flash-260425").strip()
    if not api_key or not base_url:
        result = {"status": "SKIPPED", "reason": "COZE_WORKLOAD_IDENTITY_API_KEY and COZE_INTEGRATION_MODEL_BASE_URL are required"}
        _write_artifacts(result)
        print(json.dumps(result, ensure_ascii=False))
        return 0

    result = {
        "status": "FAILED",
        "responses": False,
        "function_call": False,
        "previous_response_id": False,
        "deep_thinking": None,
        "structured_output": None,
        "streaming": None,
        "context_cache": None,
        "context_editing": None,
        "error": "",
    }
    tool = {
        "type": "function",
        "name": "capability_echo",
        "description": "Return the supplied step unchanged. This is a no-side-effect capability probe.",
        "parameters": {"type": "object", "properties": {"step": {"type": "integer"}}, "required": ["step"]},
    }
    try:
        client = OpenAI(api_key=api_key, base_url=base_url)
        first = client.responses.create(
            model=model,
            input="Call capability_echo exactly once with step 1. Do not answer in prose.",
            tools=[tool],
        )
        result["responses"] = bool(_response_id(first))
        calls = _calls(first)
        result["function_call"] = len(calls) == 1 and calls[0]["name"] == "capability_echo"
        if calls:
            second = client.responses.create(
                model=model,
                previous_response_id=_response_id(first),
                input=[{"type": "function_call_output", "call_id": calls[0]["call_id"], "output": json.dumps({"step": 1})}],
                tools=[tool],
            )
            result["previous_response_id"] = bool(_response_id(second))
        try:
            thought = client.responses.create(
                model=model,
                input="只回复：已收到。",
                extra_body={"thinking": {"type": "enabled"}},
            )
            result["deep_thinking"] = bool(_response_id(thought))
        except Exception:
            result["deep_thinking"] = False
        try:
            structured = client.responses.create(
                model=model,
                input="Return JSON with ok set to true.",
                text={
                    "format": {
                        "type": "json_schema",
                        "name": "capability_result",
                        "strict": True,
                        "schema": {
                            "type": "object",
                            "properties": {"ok": {"type": "boolean"}},
                            "required": ["ok"],
                            "additionalProperties": False,
                        },
                    },
                },
            )
            result["structured_output"] = json.loads(_output_text(structured)).get("ok") is True
        except Exception:
            result["structured_output"] = False
        try:
            cached_first = client.responses.create(
                model=model,
                input="只回复：缓存探测。",
                extra_body={"caching": {"type": "enabled"}},
            )
            cached_second = client.responses.create(
                model=model,
                previous_response_id=_response_id(cached_first),
                input="只回复：续传探测。",
                extra_body={"caching": {"type": "enabled"}},
            )
            result["context_cache"] = bool(_response_id(cached_second))
        except Exception:
            result["context_cache"] = False
        try:
            edited = client.responses.create(
                model=model,
                input="只回复：上下文编辑探测。",
                extra_body={
                    "context_management": {
                        "edits": [
                            {"type": "clear_thinking", "keep": {"type": "thinking_turns", "value": 1}},
                        ],
                    },
                },
            )
            result["context_editing"] = bool(_response_id(edited))
        except Exception:
            result["context_editing"] = False
        try:
            events = client.responses.create(
                model=model,
                input="只回复：流式探测。",
                stream=True,
            )
            result["streaming"] = any(True for _ in events)
        except Exception:
            result["streaming"] = False
        result["status"] = "PASSED" if all(result[key] for key in ("responses", "function_call", "previous_response_id")) else "FAILED"
    except Exception as exc:
        body = getattr(exc, "body", {})
        body = body if isinstance(body, dict) else {}
        error = body.get("error") if isinstance(body.get("error"), dict) else body
        details = [type(exc).__name__]
        if getattr(exc, "status_code", None) is not None:
            details.append(f"status={exc.status_code}")
        if isinstance(error, dict) and error.get("code"):
            details.append(f"code={str(error['code'])[:80]}")
        if isinstance(error, dict) and error.get("param"):
            details.append(f"param={str(error['param'])[:80]}")
        result["error"] = ";".join(details)
    result["multimodal"] = _probe_multimodal_tools(api_key=api_key, base_url=base_url, tool=tool) if result["status"] == "PASSED" else {"status": "SKIPPED", "reason": "text Responses capability probe failed"}
    _write_artifacts(result)
    print(json.dumps(result, ensure_ascii=False))
    return 0 if result["status"] == "PASSED" and result["multimodal"]["status"] in {"PASSED", "SKIPPED"} else 1


if __name__ == "__main__":
    sys.exit(main())
